version: "3.9"

services:
  hblink3:
    container_name: radio-hblink3
    hostname: radio-hblink3
    image: "cbodden/hblink3-docker:test-arm64"
    <<: [*defaults]
    ports:
      - 8888:8080/tcp
      - 9999:9000/tcp
    volumes:
      - "${STORAGE}/hblink3-docker/alias/:/alias/"
      - "${STORAGE}/hblink3-docker/hblink.cfg:/opt/HBlink3/hblink.cfg"
      - "${STORAGE}/hblink3-docker/rules.py:/opt/HBlink3/rules.py"
      - "${STORAGE}/hblink3-docker/config.py:/opt/HBmonitor/config.py"
